name: Build Environment

on: [push, pull_request]

env:
  PIPENV_ACTIVE: 1

jobs:

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: msys2do pacman --noconfirm -S -noconfirm --noprogressbar
    - run: msys2do pacman --noconfirm -U mingw-w64-*-any.pkg.tar.xz
    - run: |
        set MSYSTEM=MINGW32
        msys2do make -j
        msys2do make install
        bin/bossac --help
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: windows
        path: bin
